api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    version: 1.0.0
    title: 'Category API'
    formats:
      json:     ['application/json']
      jsonapi:  ['application/vnd.api+json']
      html:     ['text/html']