version: '2'
services:
  http-svc:
    build:
      context: .
      args:
        BUILD_ENV: 'prod'
    image: php-app-category:local
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      - mysql
  mysql:
      image: mysql:5.7.17
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: category
      command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
      volumes:
        - ./mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"

